name: doctorappointmentbookingapp
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.2"
  provider: ^6.0.0

  # Flutter Firebase Plugins
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  cloud_firestore: ^2.5.3
  firebase_database: ^8.0.0
  intl: ^0.17.0
  
  flutter_lints: ^1.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"

flutter:

  
  uses-material-design: true

  assets:
    - assets/onBoardDocr.png
    - assets/bg1.png
    - assets/category1.png
    - assets/category2.png
    - assets/category3.png
    - assets/category4.png
    - assets/category5.png
    - assets/category6.png
    - assets/category7.png
    - assets/category8.png
    - assets/doc1.png
    - assets/doc2.png
    - assets/doc3.png
    - assets/icons/

 
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
